version: "3.8"
services:
  web:
    build: ./app
    image: <ecr-repository-uri>:workshop2_web
    # ^ TASK 5 image: <ecr-repository-uri>:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=<rds-instance-endpoint>
       # ^ TASK 5 DB_HOST=<rds-instance-endpoint>
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=<ec2-instance-dns-address>
       # ^ TASK 5 VIRTUAL_HOST=<ec2-instance-dns-address>
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: <ecr-repository-uri>:workshop2_nginx
     # ^ TASK 5 image: <ecr-repository-uri>:workshop2_web
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: